apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "rbln-npu-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: rbln-operator-controller-manager-metrics-service
spec:
  ports:
    - name: https
      port: {{ .Values.operator.service.port }}
      protocol: TCP
      targetPort: {{ .Values.operator.service.targetPort }}
  selector:
    {{- include "rbln-npu-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
